# Starts Jenkins Server and Verdaccio local registry to
# Reduce bandwidth usage during testing and builds.
# Testing and deployment dockerfiles have to account for this
# And link their npm registry as follows:
# npm set registry http://verdaccio:4873/

version: "3"

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio_for_ci
    restart: always
    environment:
      - VERDACCIO_PORT=4873
      - VERDACCIO_PROTOCOL=http
    ports:
      - "4873:4873"
    expose: 
      - "4873"
    volumes:
      - ./verdaccio/conf:/verdaccio/conf
      - ./verdaccio/plugins:/verdaccio/plugins
      - verdaccio-vol:/verdaccio/storage
    networks:
      nxcicdnet:

  jenkins:
    image: dmitryr117/jenkinsci:latest
    container_name: jenkins_ci
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - jenkins-vol:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      nxcicdnet:

volumes:
  verdaccio-vol:
  jenkins-vol:
  
networks:
  nxcicdnet:

